### ISSUE TITLE
"message" event sent by another peer is being received but not processed

### ISSUE THREAD

**Issue by magestican** [rtc-io/rtc-signaller-socket.io#7]
I am currently using signaller-socket.io with quickconnect 5.4 against a backend using socket.io and rtc-switch.

I got peer1 to send messages through the socket.io backend with the rtc-switch to send announce on connect to peer2, but for some reason peer2 is not doing anything with that message.

So I am assuming rtc-signaller which is wrapped by rtc-signaller-socket.io is not picking up that message. That message contains the ID of the other discovered peer but the signaller is not doing anything with that.

This is a sample of whats happening : 

Peer1 sends : 
42["rtc-signal","/announce|cil8vcr3000003969wiq7ys33|{\"browser\":\"chrome\",\"browserVersion\":\"48.0.2564\",\"agent\":\"unknown\",\"room\":\"conftest\",\"id\":\"cil8vcr3000003969wiq7ys33\"}"]
Peer2 sends back to peer1: 
42["message","/announce|cil8vcsdl00003969ichbn18v|{\"browser\":\"chrome\",\"browserVersion\":\"48.0.2564\",\"agent\":\"unknown\",\"room\":\"conftest\",\"id\":\"cil8vcsdl00003969ichbn18v\"}"]

Do you know whats wrong?

**Comment by magestican** [comment]
Closing this, the reason it did not work is that in the documentation  says that the board should  do socket.send(data) BUT THAT IS NOT RIGHT, it should be socket.emit("rtc-signal",data)

**Comment by silviapfeiffer** [comment]
Which documentation is that? could you provide a link so we can update it? (Or better still: provide a pull request?) Thanks!

**Comment by magestican** [comment]
updated the documentation here 
https://github.com/rtc-io/rtc-switch/pull/5
